<?php

namespace AppBundle\Repository;

/**
 * BloquerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloquerRepository extends \Doctrine\ORM\EntityRepository
{
}
