<?php

namespace AppBundle\Repository;

/**
 * DemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRepository extends \Doctrine\ORM\EntityRepository
{
	public function idPresentAnnuler($session,$id)
	{
		$table2= "AppBundle:Demande";
	    $query = $this->_em->createQuery("SELECT b FROM $table2 b  WHERE b.stateRequest =0 AND (b.idUserRecever ='".$id."' AND b.idUserSender ='".$session."')");
	    return $query->getResult();
	}

	public function idPresentAccept($session,$id)
	{
		$table2= "AppBundle:Demande";
	    $query = $this->_em->createQuery("SELECT b FROM $table2 b  WHERE b.stateRequest =1 AND (b.idUserRecever ='".$session."' AND b.idUserSender ='".$id."') OR (b.idUserRecever ='".$id."' AND b.idUserSender ='".$session."')");
	    return $query->getResult();
	}

	public function idPresentConfirmer($session,$id)
	{
		$table2= "AppBundle:Demande";
	    $query = $this->_em->createQuery("SELECT b FROM $table2 b  WHERE b.stateRequest = 0 AND b.idUserRecever ='".$session."' AND b.idUserSender ='".$id."'");
	    return $query->getResult();
	}

	public function getDemandeUser($session)
   {
    $table = "AppBundle:User";
    $table2= "AppBundle:Demande";
      $query = $this->_em->createQuery("SELECT a.id,a.nom,a.prenom,a.sex,a.username,b FROM $table2 b 
        LEFT JOIN $table a
        WITH b.idUserRecever ='".$session."' AND a.id = b.idUserSender
        WHERE b.idUserRecever ='".$session."' AND b.stateRequest = 0 AND  a.id = b.idUserSender");
      $query->setMaxResults(10);
      $query->setFirstResult(0);
      return $query->getResult();
   }

   	public function getAmisUser($session)
   {
    $table = "AppBundle:User";
    $table2= "AppBundle:Demande";
      $query = $this->_em->createQuery("SELECT a.id,a.nom,a.prenom,a.sex,a.username,b FROM $table2 b 
        LEFT JOIN $table a
        WITH (b.idUserRecever ='".$session."' AND a.id = b.idUserSender) OR (b.idUserSender ='".$session."' AND a.id = b.idUserRecever)
        WHERE (b.idUserRecever ='".$session."' AND b.stateRequest = 1 AND  a.id = b.idUserSender) OR (b.idUserSender ='".$session."' AND b.stateRequest = 1 AND a.id = b.idUserRecever)");
      $query->setMaxResults(10);
      $query->setFirstResult(0);
      return $query->getResult();
   }

   public function getAllAmisUser($session)
   {
    $table = "AppBundle:User";
    $table2= "AppBundle:Demande";
      $query = $this->_em->createQuery("SELECT a.id,a.nom,a.prenom,a.sex,a.username,b FROM $table2 b 
        LEFT JOIN $table a
        WITH (b.idUserRecever ='".$session."' AND a.id = b.idUserSender) OR (b.idUserSender ='".$session."' AND a.id = b.idUserRecever)
        WHERE (b.idUserRecever ='".$session."' AND b.stateRequest = 1 AND  a.id = b.idUserSender) OR (b.idUserSender ='".$session."' AND b.stateRequest = 1 AND a.id = b.idUserRecever)");
      return $query->getResult();
   }

	 public function confirmerDemande($session,$id)
	 {
        $table2= "AppBundle:Demande";
	    $query = $this->_em->createQuery("UPDATE $table2 b SET b.stateRequest = 1 WHERE b.idUserRecever ='".$session."' AND b.idUserSender ='".$id."'");
	    return $query->getResult();
	 }

	 public function verifyIdInTable($session)
	  {
	    $table2= "AppBundle:Demande";
	    $query = $this->_em->createQuery("SELECT b FROM $table2 b WHERE b.idUserRecever ='".$session."' AND b.stateRequest = 0");
	    return $query->getResult();
	  }

	  public function checkIfUserHasSentRequest($session,$id)
	  {
	    $table2= "AppBundle:Demande";
	    $query = $this->_em->createQuery("SELECT b.idUserSender,b.idUserRecever,b.stateRequest FROM $table2 b WHERE (b.idUserSender ='".$session."' AND b.idUserRecever ='".$id."') OR (b.idUserSender ='".$id."' AND b.idUserRecever ='".$session."')");
	    return $query->getResult();
	  }

	  public function deleteRequestSent($session,$id)
	  {
	  	$table2= "AppBundle:Demande";
	    $query = $this->_em->createQuery("DELETE FROM $table2 b WHERE (b.idUserSender ='".$session."' AND b.idUserRecever ='".$id."') OR (b.idUserSender ='".$id."' AND b.idUserRecever ='".$session."')");
	    return $query->getResult();
	  }

	  
}
