<?php

namespace AppBundle\Repository;

/**
 * JaimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JaimeRepository extends \Doctrine\ORM\EntityRepository
{
	public function deletePub($session,$id)
	{
		$table = "AppBundle:Jaime";
	    $query = $this->_em->createQuery("
	    	DELETE FROM $table a 
	    	WHERE a.idUser='".$session."' AND a.idPublication ='".$id."'");
        return $query->getResult();
    }

    public function checkIfPubIsLiked($idUser,$idPub)
	{
		$table = "AppBundle:Jaime";
	    $query = $this->_em->createQuery("SELECT a FROM $table a WHERE a.idUser='".$idUser."' AND a.idPublication='".$idPub."'");
        return $query->getResult();
    }
}
