<?php

namespace AppBundle\Repository;

/**
 * MemberMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
