<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{

    public function messagenonlu($session,$id)
    {
        $table2 = "AppBundle:MemberMessage";
        $query = $this->_em->createQuery("SELECT f FROM $table2 f 
            WHERE f.stateMessage = 0 AND 
            (f.idSender='".$id."' AND f.idRecever='".$session."')
            ");
        return $query->getResult();
    }

    public function inserermsg($msg)
    {
        $table = "AppBundle:Message";
        $query = $this->_em->createQuery("
            INSERT INTO $table a(a.contentMessage,a.idGroupMessage,a.createdAt) 
            VALUES($msg,0,NOW())
            ");
    
        return $query->getResult();   
    }

	public function verifyMessage($session)
	{
		$table = "AppBundle:Message";
		$table2 = "AppBundle:MemberMessage";
		$query = $this->_em->createQuery("
			SELECT a.id,b.idMsg,b.idRecever,b.idSender FROM $table a
			LEFT JOIN $table2 b 
			WITH b.idMsg=a.id  AND (b.idSender='".$session."' OR b.idRecever='".$session."')
			WHERE a.id = b.idMsg AND (b.idSender='".$session."' OR b.idRecever='".$session."') 
			");
		return $query->getResult();
	}
	public function max_message()
	{
		$table = "AppBundle:Message";
	    $query = $this->_em->createQuery("SELECT a FROM $table a WHERE a.id =(SELECT MAX(b.id) FROM $table b)");
        return $query->getSingleResult();
    }

    public function updateState($session,$id)
	{
		$table2 = "AppBundle:MemberMessage";
	    $query = $this->_em->createQuery("UPDATE $table2 b SET b.stateMessage =1 WHERE (b.idSender ='".$session."' AND b.idRecever ='".$id."') OR (b.idSender ='".$id."' AND b.idRecever ='".$session."')");
        return $query->getResult();
    }

    public function selectUserByIdMsg($idMsg)
    {
        $table2 = "AppBundle:MemberMessage";
        $query = $this->_em->createQuery("
            SELECT f FROM $table2 f 
            WHERE f.idMsg = '".$idMsg."'");
        return $query->getSingleResult();
    }

    public function selectLast($session,$id)
    {
    	$table2 = "AppBundle:MemberMessage";
    	$query = $this->_em->createQuery("
            SELECT MAX(f.idMsg) AS idMsg FROM $table2 f 
    		WHERE
    	    (f.idSender='".$session."' AND f.idRecever='".$id."') 
    		OR 
    		(f.idSender='".$id."' AND f.idRecever='".$session."')
    		");
        return $query->getResult();
    }
    
        public function selectStateMessage($session)
    {
    	$table = "AppBundle:Message";
    	$table1 = "AppBundle:User";
    	$table2 = "AppBundle:MemberMessage";
    	
        $query = $this->_em->createQuery("
        SELECT a.id,b.stateMessage,b.idRecever FROM $table1 a 
        LEFT JOIN $table2  b 
        	WITH a.id != '".$session."' 
        	AND 
        	(a.id = b.idSender AND a.id != b.idRecever) 
        	OR 
        	(a.id !=b.idSender AND a.id = b.idRecever)  
        LEFT JOIN $table c 
            WITH c.id = b.idMsg 
        WHERE b.stateMessage=0 AND a.id !='".$session."'  
        	AND b.idMsg =(SELECT MAX(f.idMsg) FROM $table2 f WHERE (f.idSender='".$session."' AND f.idRecever=a.id)
        		OR 
        	    (f.idSender=a.id AND f.idRecever='".$session."')) 
        ORDER BY b.idMsg DESC 
	    	");
        return $query->getResult();	
    }



    public function selectlastmpuser($session)
    {
    	$table = "AppBundle:Message";
    	$table1 = "AppBundle:User";
    	$table2 = "AppBundle:MemberMessage";
    	$table3 = "AppBundle:Demande";
    	

        $query = $this->_em->createQuery("
        SELECT a.id,a.nom,a.prenom,b.idMsg,b.idSender,b.idRecever,c.contentMessage,c.createdAt,b.stateMessage FROM $table1 a 
        LEFT JOIN $table2  b 
        	WITH a.id != '".$session."' 
        	AND 
        	(a.id = b.idSender AND a.id != b.idRecever) 
        	OR 
        	(a.id !=b.idSender AND a.id = b.idRecever)  
        LEFT JOIN $table c 
            WITH c.id = b.idMsg 
        WHERE a.id !='".$session."'  
        	AND b.idMsg =(SELECT MAX(f.idMsg) FROM $table2 f WHERE (f.idSender='".$session."' AND f.idRecever=a.id)
        		OR 
        	    (f.idSender=a.id AND f.idRecever='".$session."')) 
        ORDER BY b.idMsg DESC 
	    	");
        return $query->getResult();	
    }
    
    public function select_all_mp($session,$id)
    {
    	$table = "AppBundle:Message";
    	$table1 = "AppBundle:User";
    	$table2 = "AppBundle:MemberMessage";
	    $query = $this->_em->createQuery("SELECT a.id,a.nom,a.prenom,a.username,b.idSender,c.contentMessage,c.createdAt
	    	FROM $table1 a 
	    	LEFT JOIN $table2 b 
	    	WITH a.id = b.idSender
	    	LEFT JOIN $table c
	    	WITH c.id = b.idMsg
	    	WHERE b.idMsg = c.id AND a.id = b.idSender 
	    	AND  ((b.idSender='".$session."' AND b.idRecever= '".$id."') OR (b.idSender='".$id."' AND b.idRecever= '".$session."'))
	    	ORDER BY c.createdAt DESC
	    	");
        return $query->getResult();
    }
    public function select_all_msg($session,$id,$offset,$max)
    {
    	$table = "AppBundle:Message";
    	$table1 = "AppBundle:User";
    	$table2 = "AppBundle:MemberMessage";
	    $query = $this->_em->createQuery("SELECT a.id,a.nom,a.prenom,a.username,b.idSender,c.contentMessage,c.createdAt
	    	FROM $table1 a 
	    	LEFT JOIN $table2 b 
	    	WITH a.id = b.idSender
	    	LEFT JOIN $table c
	    	WITH c.id = b.idMsg
	    	WHERE b.idMsg = c.id AND a.id = b.idSender 
	    	AND  ((b.idSender='".$session."' AND b.idRecever= '".$id."') OR (b.idSender='".$id."' AND b.idRecever= '".$session."'))
	    	ORDER BY c.createdAt DESC
	    	");
	    $query->setMaxResults($max);
        $query->setFirstResult($offset);
        return $query->getResult();
    }
}
