<?php

namespace AppBundle\Repository;

/**
 * NotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationsRepository extends \Doctrine\ORM\EntityRepository
{

	public function setStateNotif($session)
	{
		$table = "AppBundle:Notifications";
        $query = $this->_em->createQuery("
        UPDATE $table a  SET a.stateNotification = 1
        WHERE a.stateNotification = 0 AND a.recever='".$session."'
            ");
        return $query->getResult();
	}

    public function selectAllNotif($session)
    {
        $table = "AppBundle:Notifications";
        $table1 = "AppBundle:User";
        $table2 = "AppBundle:Publication";
        $query = $this->_em->createQuery("
        SELECT a.subject,a.stateNotification,a.createdAt,a.recever,a.sender,a.idPub,b.id,b.nom,b.prenom,b.username,c.content FROM $table a
        LEFT JOIN $table1 b
        WITH a.sender = b.id
        LEFT JOIN $table2 c
        WITH c.id =a.idPub
        WHERE c.id =a.idPub AND a.sender = b.id AND a.recever='".$session."'
            ");
        return $query->getResult();
    }

	public function allnotifState($session)
    {
        $table = "AppBundle:Notifications";
        $query = $this->_em->createQuery("
        SELECT a FROM $table a  
        WHERE a.stateNotification = 0 AND a.recever='".$session."'
            ");
        return $query->getResult();
    }
}
