<?php

namespace AppBundle\Repository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends \Doctrine\ORM\EntityRepository
{   
     public function selectUserQuiAime($session,$idPub)
     {
     	$table = "AppBundle:User";
		$table1 = "AppBundle:Publication";
        $table2 = "AppBundle:Jaime";

	    $query = $this->_em->createQuery("
	    	SELECT a.id,a.nom,a.prenom FROM $table2 c
	    	LEFT JOIN $table a
	    	WITH a.id = c.idUser AND c.idPublication ='".$idPub."'
	    	WHERE a.id !='".$session."' AND a.id = c.idUser AND c.idPublication ='".$idPub."'
	    	ORDER BY c.id DESC
	    	");
	    $query->setMaxResults(2);
        $query->setFirstResult(0);
        return $query->getResult();
     }

     public function selectTroisUserQuiAime($session,$idPub)
     {
     	$table = "AppBundle:User";
		$table1 = "AppBundle:Publication";
        $table2 = "AppBundle:Jaime";

	    $query = $this->_em->createQuery("
	    	SELECT a.id,a.nom,a.prenom FROM $table2 c
	    	LEFT JOIN $table a
	    	WITH a.id = c.idUser AND c.idPublication ='".$idPub."'
	    	WHERE a.id !='".$session."' AND a.id = c.idUser AND c.idPublication ='".$idPub."'
	    	ORDER BY c.id DESC
	    	");
        return $query->getResult();
     }

    public function deletePubNotif($session,$idPub)
	{
		$table = "AppBundle:Notifications";
	    $query = $this->_em->createQuery("DELETE FROM $table a 
	    	WHERE a.subject ='jaime' AND a.sender='".$session."' AND a.idPub='".$idPub."'");
        return $query->getResult();
    }
	public function selectPubById($id)
	{
		$table = "AppBundle:Publication";
		$table1 = "AppBundle:User";
	    $query = $this->_em->createQuery("
	    	SELECT b.id,b.nom,b.prenom,b.username,a.id idPub,a.idUser,a.idUserProrietaire,a.jaime,a.created_at,a.content,a.commentaires FROM $table a
	    	LEFT JOIN $table1 b
	    	WITH a.idUser = b.id
	    	WHERE a.id ='".$id."' AND a.idUser = b.id");
        return $query->getSingleResult();
	}

	public function deletePub($id)
	{
		$table = "AppBundle:Publication";
	    $query = $this->_em->createQuery("DELETE FROM $table a WHERE a.id ='".$id."'");
        return $query->getSingleResult();
    }
    public function updateJaime($id)
	{
		$table = "AppBundle:Publication";
	    $query = $this->_em->createQuery("UPDATE $table a  SET a.jaime = a.jaime +1 WHERE a.id ='".$id."'");
         return $query->getSingleResult();
    }

    public function reupdateJaime($id)
	{
		$table = "AppBundle:Publication";
	    $query = $this->_em->createQuery("UPDATE $table a  SET a.jaime = a.jaime-1 WHERE a.id ='".$id."'");
         return $query->getSingleResult();
    }
}
