<?php


namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{


  public function selectPub($id)
  {
    $table = "AppBundle:User";
    $table2 = "AppBundle:Publication";
      $query = $this->_em->createQuery("SELECT a.id idP,a.username,a.nom,a.prenom,b.id,b.idUser,b.idUserProrietaire,b.content,b.jaime,b.commentaires,b.created_at FROM $table a LEFT JOIN $table2 b WITH a.id = b.idUser WHERE b.idUserProrietaire = '".$id."' ORDER BY b.created_at DESC");
      $query->setMaxResults(5);
      $query->setFirstResult(0);
        return $query->getResult();
  }

  public function searchOtherId($id)
  {
    $table= "AppBundle:User";
    $query = $this->_em->createQuery("SELECT a.id,a.nom,a.prenom,a.sex,a.username,a.activite,a.ville,a.sex,a.categorie,a.jour,a.mois,a.annee FROM $table a WHERE a.id != '".$id."' ORDER BY a.id ASC");
    $query->setMaxResults(10);
    $query->setFirstResult(0);
     return $query->getResult();
  }  


	public function getOneUser($id)
	{
	 return $this
        ->createQueryBuilder('e')
        ->where('e.id = :parcsimmobilier')
        ->setParameter('id', $id);
	}


  public function checkIfInformationIsUpdated($id)
  {
   $query = $this->_em->createQuery("SELECT a.nom,a.prenom,a.ville FROM AppBundle:User a WHERE a.id ='".$id."'");
     return $query->getSingleResult();
  }



   public function updateInfo($id,$nom,$prenom,$jour,$mois,$annee,$lieunaissance,$ville,$sex,$categorie,$activite)
  {   
    $query = $this->_em->createQuery("UPDATE AppBundle:User a SET a.nom='".$nom."',a.prenom='".$prenom."',a.jour='".$jour."',a.mois='".$mois."',a.annee='".$annee."',a.lieuNaissance='".$lieunaissance."',a.ville='".$ville."',a.sex='".$sex."',a.categorie='".$categorie."',a.activite='".$activite."'  WHERE a.id = '".$id."'");
       // $query->setParameter('id',$id);
        return $query->getSingleResult();
   }

   
 }